- name: Install packages
  hosts: frontend
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - mysql
    - nginx
    - zip
    - wget
